
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// HOK单位配置
    /// </summary>
    public hok.TbUnit TbUnit {get; }
    /// <summary>
    /// HOK英雄配置
    /// </summary>
    public hok.TbHero TbHero {get; }
    /// <summary>
    /// HOK地图配置
    /// </summary>
    public hok.TbMap TbMap {get; }
    /// <summary>
    /// HOK技能配置
    /// </summary>
    public hok.TbSkill TbSkill {get; }
    /// <summary>
    /// HOKBuff配置(多态)
    /// </summary>
    public hok.TbBuff TbBuff {get; }
    /// <summary>
    /// HOK目标规则配置(占位)
    /// </summary>
    public hok.TbTargetRule TbTargetRule {get; }
    /// <summary>
    /// HOK客户端手感配置
    /// </summary>
    public hok.TbClientSetting TbClientSetting {get; }
    /// <summary>
    /// HOK客户端音频配置
    /// </summary>
    public hok.TbClientAudio TbClientAudio {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbUnit = new hok.TbUnit(loader("hok_tbunit"));
        TbHero = new hok.TbHero(loader("hok_tbhero"));
        TbMap = new hok.TbMap(loader("hok_tbmap"));
        TbSkill = new hok.TbSkill(loader("hok_tbskill"));
        TbBuff = new hok.TbBuff(loader("hok_tbbuff"));
        TbTargetRule = new hok.TbTargetRule(loader("hok_tbtargetrule"));
        TbClientSetting = new hok.TbClientSetting(loader("hok_tbclientsetting"));
        TbClientAudio = new hok.TbClientAudio(loader("hok_tbclientaudio"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbUnit.ResolveRef(this);
        TbHero.ResolveRef(this);
        TbMap.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbTargetRule.ResolveRef(this);
        TbClientSetting.ResolveRef(this);
        TbClientAudio.ResolveRef(this);
    }
}

}
