
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum AttachType
    {
        None = 0,
        /// <summary>
        /// 施法者
        /// </summary>
        Caster = 1,
        /// <summary>
        /// 目标
        /// </summary>
        Target = 2,
        /// <summary>
        /// 独立
        /// </summary>
        Indie = 3,
        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 4,
    }

} 

