
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// Buff配置基类(多态)
/// </summary>
public abstract partial class BuffCfg : Luban.BeanBase
{
    public BuffCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuffID = _buf.ReadInt();
        BuffName = _buf.ReadString();
        BuffType = (hok.BuffType)_buf.ReadInt();
        Attacher = (hok.AttachType)_buf.ReadInt();
        if(_buf.ReadBool()){ Impacter = global::GameConfig.hok.TargetCfg.DeserializeTargetCfg(_buf); } else { Impacter = null; }
        BuffDelay = _buf.ReadInt();
        BuffInterval = _buf.ReadInt();
        BuffDuration = _buf.ReadInt();
        StaticPosType = (hok.StaticPosType)_buf.ReadInt();
        BuffAudio = _buf.ReadString();
        BuffEffect = _buf.ReadString();
        HitTickAudio = _buf.ReadString();
    }

    public static BuffCfg DeserializeBuffCfg(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case hok.CommonBuffCfg.__ID__: return new hok.CommonBuffCfg(_buf);
            case hok.HPCureBuffCfg.__ID__: return new hok.HPCureBuffCfg(_buf);
            case hok.MoveSpeedBuffCfg.__ID__: return new hok.MoveSpeedBuffCfg(_buf);
            case hok.CommonModifySkillBuffCfg.__ID__: return new hok.CommonModifySkillBuffCfg(_buf);
            case hok.ArthurMarkBuffCfg.__ID__: return new hok.ArthurMarkBuffCfg(_buf);
            case hok.TargetFlashMoveBuffCfg.__ID__: return new hok.TargetFlashMoveBuffCfg(_buf);
            case hok.ExecuteDamageBuffCfg.__ID__: return new hok.ExecuteDamageBuffCfg(_buf);
            case hok.DamageDynamicGroupBuffCfg.__ID__: return new hok.DamageDynamicGroupBuffCfg(_buf);
            case hok.DamageStaticGroupBuffCfg.__ID__: return new hok.DamageStaticGroupBuffCfg(_buf);
            case hok.StunDynamicTimeBuffCfg.__ID__: return new hok.StunDynamicTimeBuffCfg(_buf);
            case hok.HouyiPasvAttackSpeedBuffCfg.__ID__: return new hok.HouyiPasvAttackSpeedBuffCfg(_buf);
            case hok.HouyiMultipleSkillModifyBuffCfg.__ID__: return new hok.HouyiMultipleSkillModifyBuffCfg(_buf);
            case hok.HouyiScatterSkillModifyBuffCfg.__ID__: return new hok.HouyiScatterSkillModifyBuffCfg(_buf);
            case hok.HouyiScatterArrowBuffCfg.__ID__: return new hok.HouyiScatterArrowBuffCfg(_buf);
            case hok.HouyiMultipleArrowBuffCfg.__ID__: return new hok.HouyiMultipleArrowBuffCfg(_buf);
            case hok.HouyiMixedMultiScatterBuffCfg.__ID__: return new hok.HouyiMixedMultiScatterBuffCfg(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 配置唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff业务ID
    /// </summary>
    public readonly int BuffID;
    /// <summary>
    /// Buff名称
    /// </summary>
    public readonly string BuffName;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly hok.BuffType BuffType;
    /// <summary>
    /// 附着目标
    /// </summary>
    public readonly hok.AttachType Attacher;
    /// <summary>
    /// 作用目标
    /// </summary>
    public readonly hok.TargetCfg Impacter;
    /// <summary>
    /// 延迟ms
    /// </summary>
    public readonly int BuffDelay;
    /// <summary>
    /// 间隔ms
    /// </summary>
    public readonly int BuffInterval;
    /// <summary>
    /// 持续时间ms
    /// </summary>
    public readonly int BuffDuration;
    /// <summary>
    /// 静态位置类型
    /// </summary>
    public readonly hok.StaticPosType StaticPosType;
    /// <summary>
    /// Buff音效
    /// </summary>
    public readonly string BuffAudio;
    /// <summary>
    /// Buff特效
    /// </summary>
    public readonly string BuffEffect;
    /// <summary>
    /// 命中音效
    /// </summary>
    public readonly string HitTickAudio;
   

    public virtual void ResolveRef(Tables tables)
    {
        Impacter?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "}";
    }
}
}

