
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum BuffType
    {
        None = 0,
        /// <summary>
        /// 治疗
        /// </summary>
        HPCure = 1,
        /// <summary>
        /// 技能修改
        /// </summary>
        ModifySkill = 2,
        /// <summary>
        /// 单体加速
        /// </summary>
        MoveSpeed_Single = 3,
        /// <summary>
        /// 标记伤害
        /// </summary>
        ArthurMark = 4,
        /// <summary>
        /// 沉默
        /// </summary>
        Silense = 5,
        /// <summary>
        /// 目标闪现
        /// </summary>
        TargetFlashMove = 6,
        /// <summary>
        /// 方向闪现
        /// </summary>
        DirectionFlashMove = 7,
        /// <summary>
        /// 百分比斩杀
        /// </summary>
        ExecuteDamage = 8,
        /// <summary>
        /// 群体击飞
        /// </summary>
        Knockup_Group = 9,
        /// <summary>
        /// 动态眩晕
        /// </summary>
        Stun_Single_DynamicTime = 10,
        /// <summary>
        /// 后羿主动技能修改
        /// </summary>
        HouyiActiveSkillModify = 11,
        /// <summary>
        /// 散射
        /// </summary>
        Scatter = 12,
        /// <summary>
        /// 后羿被动攻速
        /// </summary>
        HouyiPasvAttackSpeed = 13,
        /// <summary>
        /// 后羿被动技能修改
        /// </summary>
        HouyiPasvSkillModify = 14,
        /// <summary>
        /// 后羿被动多重射击
        /// </summary>
        HouyiPasvMultiArrow = 15,
        /// <summary>
        /// 后羿混合多重散射
        /// </summary>
        HouyiMixedMultiScatter = 16,
        /// <summary>
        /// 动态群体移速
        /// </summary>
        MoveSpeed_DynamicGroup = 17,
        /// <summary>
        /// 静态群体移速
        /// </summary>
        MoveSpeed_StaticGroup = 18,
        /// <summary>
        /// 动态群体伤害
        /// </summary>
        Damage_DynamicGroup = 19,
        /// <summary>
        /// 静态群体伤害
        /// </summary>
        Damage_StaticGroup = 20,
        /// <summary>
        /// 移动攻击
        /// </summary>
        MoveAttack = 21,
    }

} 

