
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum BulletType
    {
        /// <summary>
        /// UI方向
        /// </summary>
        UIDirection = 0,
        /// <summary>
        /// UI位置
        /// </summary>
        UIPosition = 1,
        /// <summary>
        /// 技能目标
        /// </summary>
        SkillTarget = 2,
        /// <summary>
        /// Buff搜索
        /// </summary>
        BuffSearch = 3,
    }

} 

