
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 子弹配置
/// </summary>
public sealed partial class BulletCfg : Luban.BeanBase
{
    public BulletCfg(ByteBuf _buf) 
    {
        BulletType = (hok.BulletType)_buf.ReadInt();
        BulletName = _buf.ReadString();
        ResPath = _buf.ReadString();
        BulletSpeed = _buf.ReadFloat();
        BulletSize = _buf.ReadFloat();
        BulletHeight = _buf.ReadFloat();
        BulletOffset = _buf.ReadFloat();
        BulletDelay = _buf.ReadInt();
        CanBlock = _buf.ReadBool();
        if(_buf.ReadBool()){ Impacter = global::GameConfig.hok.TargetCfg.DeserializeTargetCfg(_buf); } else { Impacter = null; }
        BulletDuration = _buf.ReadInt();
    }

    public static BulletCfg DeserializeBulletCfg(ByteBuf _buf)
    {
        return new hok.BulletCfg(_buf);
    }

    /// <summary>
    /// 子弹类型
    /// </summary>
    public readonly hok.BulletType BulletType;
    /// <summary>
    /// 子弹名称
    /// </summary>
    public readonly string BulletName;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 大小
    /// </summary>
    public readonly float BulletSize;
    /// <summary>
    /// 高度
    /// </summary>
    public readonly float BulletHeight;
    /// <summary>
    /// 偏移
    /// </summary>
    public readonly float BulletOffset;
    /// <summary>
    /// 延迟ms
    /// </summary>
    public readonly int BulletDelay;
    /// <summary>
    /// 是否可阻挡
    /// </summary>
    public readonly bool CanBlock;
    /// <summary>
    /// 受影响目标
    /// </summary>
    public readonly hok.TargetCfg Impacter;
    /// <summary>
    /// 持续时间ms
    /// </summary>
    public readonly int BulletDuration;
   
    public const int __ID__ = 516550328;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Impacter?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "bulletType:" + BulletType + ","
        + "bulletName:" + BulletName + ","
        + "resPath:" + ResPath + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "bulletSize:" + BulletSize + ","
        + "bulletHeight:" + BulletHeight + ","
        + "bulletOffset:" + BulletOffset + ","
        + "bulletDelay:" + BulletDelay + ","
        + "canBlock:" + CanBlock + ","
        + "impacter:" + Impacter + ","
        + "bulletDuration:" + BulletDuration + ","
        + "}";
    }
}
}

