
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
public sealed partial class ClientAudio : Luban.BeanBase
{
    public ClientAudio(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        Group = _buf.ReadString();
        Path = _buf.ReadString();
        Comment = _buf.ReadString();
    }

    public static ClientAudio DeserializeClientAudio(ByteBuf _buf)
    {
        return new hok.ClientAudio(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 业务键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 分类
    /// </summary>
    public readonly string Group;
    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 注释
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -630846463;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "group:" + Group + ","
        + "path:" + Path + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

