
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
public sealed partial class ClientSetting : Luban.BeanBase
{
    public ClientSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        OpDis = _buf.ReadInt();
        SkillOPDis = _buf.ReadInt();
        SkillCancelDis = _buf.ReadInt();
    }

    public static ClientSetting DeserializeClientSetting(ByteBuf _buf)
    {
        return new hok.ClientSetting(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 摇杆触发距离
    /// </summary>
    public readonly int OpDis;
    /// <summary>
    /// 技能摇杆距离
    /// </summary>
    public readonly int SkillOPDis;
    /// <summary>
    /// 技能取消距离
    /// </summary>
    public readonly int SkillCancelDis;
   
    public const int __ID__ = 1994137531;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "opDis:" + OpDis + ","
        + "skillOPDis:" + SkillOPDis + ","
        + "skillCancelDis:" + SkillCancelDis + ","
        + "}";
    }
}
}

