
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 普攻替换Buff
/// </summary>
public sealed partial class CommonModifySkillBuffCfg : hok.BuffCfg
{
    public CommonModifySkillBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        OriginalID = _buf.ReadInt();
        ReplaceID = _buf.ReadInt();
    }

    public static CommonModifySkillBuffCfg DeserializeCommonModifySkillBuffCfg(ByteBuf _buf)
    {
        return new hok.CommonModifySkillBuffCfg(_buf);
    }

    /// <summary>
    /// 原技能ID
    /// </summary>
    public readonly int OriginalID;
    /// <summary>
    /// 替换技能ID
    /// </summary>
    public readonly int ReplaceID;
   
    public const int __ID__ = 1354437935;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "originalID:" + OriginalID + ","
        + "replaceID:" + ReplaceID + ","
        + "}";
    }
}
}

