
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 通用Buff
/// </summary>
public sealed partial class CommonBuffCfg : hok.BuffCfg
{
    public CommonBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static CommonBuffCfg DeserializeCommonBuffCfg(ByteBuf _buf)
    {
        return new hok.CommonBuffCfg(_buf);
    }

   
    public const int __ID__ = 1074014812;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "}";
    }
}
}

