
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 动态群体伤害Buff
/// </summary>
public sealed partial class DamageDynamicGroupBuffCfg : hok.BuffCfg
{
    public DamageDynamicGroupBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        Damage = _buf.ReadInt();
    }

    public static DamageDynamicGroupBuffCfg DeserializeDamageDynamicGroupBuffCfg(ByteBuf _buf)
    {
        return new hok.DamageDynamicGroupBuffCfg(_buf);
    }

    /// <summary>
    /// 伤害值
    /// </summary>
    public readonly int Damage;
   
    public const int __ID__ = -340423624;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "damage:" + Damage + ","
        + "}";
    }
}
}

