
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UnitId = _buf.ReadInt();
        UnitId_Ref = null;
        Selectable = _buf.ReadBool();
    }

    public static Hero DeserializeHero(ByteBuf _buf)
    {
        return new hok.Hero(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单位ID
    /// </summary>
    public readonly int UnitId;
    public hok.Unit UnitId_Ref;
    /// <summary>
    /// 是否可选
    /// </summary>
    public readonly bool Selectable;
   
    public const int __ID__ = -594611324;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnitId_Ref = tables.TbUnit.GetOrDefault(UnitId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "unitId:" + UnitId + ","
        + "selectable:" + Selectable + ","
        + "}";
    }
}
}

