
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 后羿多重技能修改Buff
/// </summary>
public sealed partial class HouyiMultipleSkillModifyBuffCfg : hok.BuffCfg
{
    public HouyiMultipleSkillModifyBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        OriginalID = _buf.ReadInt();
        PowerID = _buf.ReadInt();
        SuperPowerID = _buf.ReadInt();
        TriggerOverCount = _buf.ReadInt();
        ResetTime = _buf.ReadInt();
    }

    public static HouyiMultipleSkillModifyBuffCfg DeserializeHouyiMultipleSkillModifyBuffCfg(ByteBuf _buf)
    {
        return new hok.HouyiMultipleSkillModifyBuffCfg(_buf);
    }

    /// <summary>
    /// 原技能ID
    /// </summary>
    public readonly int OriginalID;
    /// <summary>
    /// 强化ID
    /// </summary>
    public readonly int PowerID;
    /// <summary>
    /// 超强化ID
    /// </summary>
    public readonly int SuperPowerID;
    /// <summary>
    /// 触发叠加数
    /// </summary>
    public readonly int TriggerOverCount;
    /// <summary>
    /// 重置时间ms
    /// </summary>
    public readonly int ResetTime;
   
    public const int __ID__ = 1729150218;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "originalID:" + OriginalID + ","
        + "powerID:" + PowerID + ","
        + "superPowerID:" + SuperPowerID + ","
        + "triggerOverCount:" + TriggerOverCount + ","
        + "resetTime:" + ResetTime + ","
        + "}";
    }
}
}

