
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 后羿混合多重散射Buff
/// </summary>
public sealed partial class HouyiMixedMultiScatterBuffCfg : hok.BuffCfg
{
    public HouyiMixedMultiScatterBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        ScatterCount = _buf.ReadInt();
        if(_buf.ReadBool()){ TargetCfg = global::GameConfig.hok.TargetCfg.DeserializeTargetCfg(_buf); } else { TargetCfg = null; }
        DamagePct = _buf.ReadInt();
        ArrowCount = _buf.ReadInt();
        ArrowDelay = _buf.ReadInt();
        PosOffset = _buf.ReadFloat();
    }

    public static HouyiMixedMultiScatterBuffCfg DeserializeHouyiMixedMultiScatterBuffCfg(ByteBuf _buf)
    {
        return new hok.HouyiMixedMultiScatterBuffCfg(_buf);
    }

    /// <summary>
    /// 散射数量
    /// </summary>
    public readonly int ScatterCount;
    /// <summary>
    /// 散射目标
    /// </summary>
    public readonly hok.TargetCfg TargetCfg;
    /// <summary>
    /// 伤害百分比
    /// </summary>
    public readonly int DamagePct;
    /// <summary>
    /// 箭数量
    /// </summary>
    public readonly int ArrowCount;
    /// <summary>
    /// 箭延迟ms
    /// </summary>
    public readonly int ArrowDelay;
    /// <summary>
    /// 位置偏移
    /// </summary>
    public readonly float PosOffset;
   
    public const int __ID__ = -1590778427;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        TargetCfg?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "scatterCount:" + ScatterCount + ","
        + "targetCfg:" + TargetCfg + ","
        + "damagePct:" + DamagePct + ","
        + "arrowCount:" + ArrowCount + ","
        + "arrowDelay:" + ArrowDelay + ","
        + "posOffset:" + PosOffset + ","
        + "}";
    }
}
}

