
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 后羿多重箭Buff
/// </summary>
public sealed partial class HouyiMultipleArrowBuffCfg : hok.BuffCfg
{
    public HouyiMultipleArrowBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        ArrowCount = _buf.ReadInt();
        ArrowDelay = _buf.ReadInt();
        PosOffset = _buf.ReadFloat();
    }

    public static HouyiMultipleArrowBuffCfg DeserializeHouyiMultipleArrowBuffCfg(ByteBuf _buf)
    {
        return new hok.HouyiMultipleArrowBuffCfg(_buf);
    }

    /// <summary>
    /// 箭数量
    /// </summary>
    public readonly int ArrowCount;
    /// <summary>
    /// 箭延迟ms
    /// </summary>
    public readonly int ArrowDelay;
    /// <summary>
    /// 位置偏移
    /// </summary>
    public readonly float PosOffset;
   
    public const int __ID__ = 64537772;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "arrowCount:" + ArrowCount + ","
        + "arrowDelay:" + ArrowDelay + ","
        + "posOffset:" + PosOffset + ","
        + "}";
    }
}
}

