
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 后羿被动攻速Buff
/// </summary>
public sealed partial class HouyiPasvAttackSpeedBuffCfg : hok.BuffCfg
{
    public HouyiPasvAttackSpeedBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        OverCount = _buf.ReadInt();
        SpeedAddtion = _buf.ReadInt();
        ResetTime = _buf.ReadInt();
    }

    public static HouyiPasvAttackSpeedBuffCfg DeserializeHouyiPasvAttackSpeedBuffCfg(ByteBuf _buf)
    {
        return new hok.HouyiPasvAttackSpeedBuffCfg(_buf);
    }

    /// <summary>
    /// 叠加次数
    /// </summary>
    public readonly int OverCount;
    /// <summary>
    /// 攻速加成
    /// </summary>
    public readonly int SpeedAddtion;
    /// <summary>
    /// 重置时间ms
    /// </summary>
    public readonly int ResetTime;
   
    public const int __ID__ = 666562842;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "overCount:" + OverCount + ","
        + "speedAddtion:" + SpeedAddtion + ","
        + "resetTime:" + ResetTime + ","
        + "}";
    }
}
}

