
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
public sealed partial class Map : Luban.BeanBase
{
    public Map(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BlueBorn = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf));
        RedBorn = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf));
        {int n0 = _buf.ReadSize(); TowerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TowerIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); TowerPositions = new System.Collections.Generic.List<UnityEngine.Vector3>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector3 _e0;  _e0 = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf)); TowerPositions.Add(_e0);}}
        BornDelay = _buf.ReadInt();
        BornInterval = _buf.ReadInt();
        WaveInterval = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BlueSoldierIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BlueSoldierIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BlueSoldierPositions = new System.Collections.Generic.List<UnityEngine.Vector3>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector3 _e0;  _e0 = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf)); BlueSoldierPositions.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RedSoldierIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RedSoldierIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RedSoldierPositions = new System.Collections.Generic.List<UnityEngine.Vector3>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Vector3 _e0;  _e0 = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf)); RedSoldierPositions.Add(_e0);}}
    }

    public static Map DeserializeMap(ByteBuf _buf)
    {
        return new hok.Map(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 蓝方出生点
    /// </summary>
    public readonly UnityEngine.Vector3 BlueBorn;
    /// <summary>
    /// 红方出生点
    /// </summary>
    public readonly UnityEngine.Vector3 RedBorn;
    /// <summary>
    /// 防御塔ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> TowerIds;
    /// <summary>
    /// 防御塔位置
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector3> TowerPositions;
    /// <summary>
    /// 出兵延迟
    /// </summary>
    public readonly int BornDelay;
    /// <summary>
    /// 出兵间隔
    /// </summary>
    public readonly int BornInterval;
    /// <summary>
    /// 波次间隔
    /// </summary>
    public readonly int WaveInterval;
    /// <summary>
    /// 蓝方小兵ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> BlueSoldierIds;
    /// <summary>
    /// 蓝方小兵位置
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector3> BlueSoldierPositions;
    /// <summary>
    /// 红方小兵ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> RedSoldierIds;
    /// <summary>
    /// 红方小兵位置
    /// </summary>
    public readonly System.Collections.Generic.List<UnityEngine.Vector3> RedSoldierPositions;
   
    public const int __ID__ = 1089202322;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "blueBorn:" + BlueBorn + ","
        + "redBorn:" + RedBorn + ","
        + "towerIds:" + Luban.StringUtil.CollectionToString(TowerIds) + ","
        + "towerPositions:" + Luban.StringUtil.CollectionToString(TowerPositions) + ","
        + "bornDelay:" + BornDelay + ","
        + "bornInterval:" + BornInterval + ","
        + "waveInterval:" + WaveInterval + ","
        + "blueSoldierIds:" + Luban.StringUtil.CollectionToString(BlueSoldierIds) + ","
        + "blueSoldierPositions:" + Luban.StringUtil.CollectionToString(BlueSoldierPositions) + ","
        + "redSoldierIds:" + Luban.StringUtil.CollectionToString(RedSoldierIds) + ","
        + "redSoldierPositions:" + Luban.StringUtil.CollectionToString(RedSoldierPositions) + ","
        + "}";
    }
}
}

