
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 移速Buff
/// </summary>
public sealed partial class MoveSpeedBuffCfg : hok.BuffCfg
{
    public MoveSpeedBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        Amount = _buf.ReadInt();
    }

    public static MoveSpeedBuffCfg DeserializeMoveSpeedBuffCfg(ByteBuf _buf)
    {
        return new hok.MoveSpeedBuffCfg(_buf);
    }

    /// <summary>
    /// 移速增减百分比
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = 2054356933;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

