
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum ReleaseMode
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 点击施放
        /// </summary>
        Click = 1,
        /// <summary>
        /// 位置施放
        /// </summary>
        Postion = 2,
        /// <summary>
        /// 方向施放
        /// </summary>
        Direction = 3,
    }

} 

