
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum SelectRule
    {
        None = 0,
        /// <summary>
        /// 最少总血量
        /// </summary>
        MinHPValue = 1,
        /// <summary>
        /// 最少百分比血量
        /// </summary>
        MinHPPercent = 2,
        /// <summary>
        /// 靠近目标单个
        /// </summary>
        TargetClosestSingle = 3,
        /// <summary>
        /// 靠近位置单个
        /// </summary>
        PositionClosestSingle = 4,
        /// <summary>
        /// 靠近目标多个
        /// </summary>
        TargetClosetMultiple = 5,
        /// <summary>
        /// 靠近位置多个
        /// </summary>
        PositionClosestMultiple = 6,
        /// <summary>
        /// 所有英雄
        /// </summary>
        Hero = 7,
    }

} 

