
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 技能配置
/// </summary>
public sealed partial class SkillCfg : Luban.BeanBase
{
    public SkillCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillID = _buf.ReadInt();
        IconName = _buf.ReadString();
        AniName = _buf.ReadString();
        ReleaseMode = (hok.ReleaseMode)_buf.ReadInt();
        if(_buf.ReadBool()){ TargetCfg = global::GameConfig.hok.TargetCfg.DeserializeTargetCfg(_buf); } else { TargetCfg = null; }
        if(_buf.ReadBool()){ BulletCfg = global::GameConfig.hok.BulletCfg.DeserializeBulletCfg(_buf); } else { BulletCfg = null; }
        CdTime = _buf.ReadInt();
        SpellTime = _buf.ReadInt();
        IsNormalAttack = _buf.ReadBool();
        SkillTime = _buf.ReadInt();
        Damage = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BuffIDArr = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BuffIDArr.Add(_e0);}}
        AudioStart = _buf.ReadString();
        AudioWork = _buf.ReadString();
        AudioHit = _buf.ReadString();
    }

    public static SkillCfg DeserializeSkillCfg(ByteBuf _buf)
    {
        return new hok.SkillCfg(_buf);
    }

    /// <summary>
    /// 配置唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能业务ID
    /// </summary>
    public readonly int SkillID;
    /// <summary>
    /// 技能图标
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 施法动画
    /// </summary>
    public readonly string AniName;
    /// <summary>
    /// 施放方式
    /// </summary>
    public readonly hok.ReleaseMode ReleaseMode;
    /// <summary>
    /// 目标配置
    /// </summary>
    public readonly hok.TargetCfg TargetCfg;
    /// <summary>
    /// 弹道配置
    /// </summary>
    public readonly hok.BulletCfg BulletCfg;
    /// <summary>
    /// CD时间ms
    /// </summary>
    public readonly int CdTime;
    /// <summary>
    /// 施法前摇ms
    /// </summary>
    public readonly int SpellTime;
    /// <summary>
    /// 是否普攻
    /// </summary>
    public readonly bool IsNormalAttack;
    /// <summary>
    /// 技能全长时间ms
    /// </summary>
    public readonly int SkillTime;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 附加Buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffIDArr;
    /// <summary>
    /// 施法开始音效
    /// </summary>
    public readonly string AudioStart;
    /// <summary>
    /// 施法成功音效
    /// </summary>
    public readonly string AudioWork;
    /// <summary>
    /// 命中音效
    /// </summary>
    public readonly string AudioHit;
   
    public const int __ID__ = -236970275;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TargetCfg?.ResolveRef(tables);
        BulletCfg?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillID:" + SkillID + ","
        + "iconName:" + IconName + ","
        + "aniName:" + AniName + ","
        + "releaseMode:" + ReleaseMode + ","
        + "targetCfg:" + TargetCfg + ","
        + "bulletCfg:" + BulletCfg + ","
        + "cdTime:" + CdTime + ","
        + "spellTime:" + SpellTime + ","
        + "isNormalAttack:" + IsNormalAttack + ","
        + "skillTime:" + SkillTime + ","
        + "damage:" + Damage + ","
        + "buffIDArr:" + Luban.StringUtil.CollectionToString(BuffIDArr) + ","
        + "audioStart:" + AudioStart + ","
        + "audioWork:" + AudioWork + ","
        + "audioHit:" + AudioHit + ","
        + "}";
    }
}
}

