
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.hok
{ 
    public enum StaticPosType
    {
        None = 0,
        /// <summary>
        /// 施法者位置
        /// </summary>
        SkillCasterPos = 1,
        /// <summary>
        /// 锁定目标位置
        /// </summary>
        SkillLockTargetPos = 2,
        /// <summary>
        /// 子弹命中位置
        /// </summary>
        BulletHitTargetPos = 3,
        /// <summary>
        /// UI输入位置
        /// </summary>
        UIInputPos = 4,
    }

} 

