
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 动态眩晕Buff
/// </summary>
public sealed partial class StunDynamicTimeBuffCfg : hok.BuffCfg
{
    public StunDynamicTimeBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        MinStunTime = _buf.ReadInt();
        MaxStunTime = _buf.ReadInt();
    }

    public static StunDynamicTimeBuffCfg DeserializeStunDynamicTimeBuffCfg(ByteBuf _buf)
    {
        return new hok.StunDynamicTimeBuffCfg(_buf);
    }

    /// <summary>
    /// 最小眩晕ms
    /// </summary>
    public readonly int MinStunTime;
    /// <summary>
    /// 最大眩晕ms
    /// </summary>
    public readonly int MaxStunTime;
   
    public const int __ID__ = 760234281;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "minStunTime:" + MinStunTime + ","
        + "maxStunTime:" + MaxStunTime + ","
        + "}";
    }
}
}

