
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 目标配置
/// </summary>
public sealed partial class TargetCfg : Luban.BeanBase
{
    public TargetCfg(ByteBuf _buf) 
    {
        TargetTeam = (hok.TargetTeam)_buf.ReadInt();
        SelectRule = (hok.SelectRule)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); TargetTypeArr = new System.Collections.Generic.List<hok.UnitType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { hok.UnitType _e0;  _e0 = (hok.UnitType)_buf.ReadInt(); TargetTypeArr.Add(_e0);}}
        SelectRange = _buf.ReadFloat();
        SearchDis = _buf.ReadFloat();
    }

    public static TargetCfg DeserializeTargetCfg(ByteBuf _buf)
    {
        return new hok.TargetCfg(_buf);
    }

    /// <summary>
    /// 目标队伍
    /// </summary>
    public readonly hok.TargetTeam TargetTeam;
    /// <summary>
    /// 选择规则
    /// </summary>
    public readonly hok.SelectRule SelectRule;
    /// <summary>
    /// 目标类型数组
    /// </summary>
    public readonly System.Collections.Generic.List<hok.UnitType> TargetTypeArr;
    /// <summary>
    /// 查找范围
    /// </summary>
    public readonly float SelectRange;
    /// <summary>
    /// 移动攻击搜索距离
    /// </summary>
    public readonly float SearchDis;
   
    public const int __ID__ = -1562418231;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "targetTeam:" + TargetTeam + ","
        + "selectRule:" + SelectRule + ","
        + "targetTypeArr:" + Luban.StringUtil.CollectionToString(TargetTypeArr) + ","
        + "selectRange:" + SelectRange + ","
        + "searchDis:" + SearchDis + ","
        + "}";
    }
}
}

