
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// 目标闪现Buff
/// </summary>
public sealed partial class TargetFlashMoveBuffCfg : hok.BuffCfg
{
    public TargetFlashMoveBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        Offset = _buf.ReadFloat();
    }

    public static TargetFlashMoveBuffCfg DeserializeTargetFlashMoveBuffCfg(ByteBuf _buf)
    {
        return new hok.TargetFlashMoveBuffCfg(_buf);
    }

    /// <summary>
    /// 偏移距离
    /// </summary>
    public readonly float Offset;
   
    public const int __ID__ = -1910637397;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffID:" + BuffID + ","
        + "buffName:" + BuffName + ","
        + "buffType:" + BuffType + ","
        + "attacher:" + Attacher + ","
        + "impacter:" + Impacter + ","
        + "buffDelay:" + BuffDelay + ","
        + "buffInterval:" + BuffInterval + ","
        + "buffDuration:" + BuffDuration + ","
        + "staticPosType:" + StaticPosType + ","
        + "buffAudio:" + BuffAudio + ","
        + "buffEffect:" + BuffEffect + ","
        + "hitTickAudio:" + HitTickAudio + ","
        + "offset:" + Offset + ","
        + "}";
    }
}
}

