
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// HOKBuff配置(多态)
/// </summary>
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, hok.BuffCfg> _dataMap;
    private readonly System.Collections.Generic.List<hok.BuffCfg> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hok.BuffCfg>(n);
        _dataList = new System.Collections.Generic.List<hok.BuffCfg>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hok.BuffCfg _v;
            _v = global::GameConfig.hok.BuffCfg.DeserializeBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, hok.BuffCfg> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<hok.BuffCfg> DataList => _dataList;

    public T GetOrDefaultAs<T>(int key) where T : hok.BuffCfg => _dataMap.TryGetValue(key, out var v) ? (T)v : default;
    public T GetAs<T>(int key) where T : hok.BuffCfg => (T)_dataMap[key];
    public hok.BuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hok.BuffCfg Get(int key) => _dataMap[key];
    public hok.BuffCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

