
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// HOK客户端手感配置
/// </summary>
public partial class TbClientSetting
{
    private readonly System.Collections.Generic.Dictionary<int, hok.ClientSetting> _dataMap;
    private readonly System.Collections.Generic.List<hok.ClientSetting> _dataList;
    
    public TbClientSetting(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hok.ClientSetting>(n);
        _dataList = new System.Collections.Generic.List<hok.ClientSetting>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hok.ClientSetting _v;
            _v = global::GameConfig.hok.ClientSetting.DeserializeClientSetting(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, hok.ClientSetting> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<hok.ClientSetting> DataList => _dataList;

    public hok.ClientSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hok.ClientSetting Get(int key) => _dataMap[key];
    public hok.ClientSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

