
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// HOK技能配置
/// </summary>
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, hok.SkillCfg> _dataMap;
    private readonly System.Collections.Generic.List<hok.SkillCfg> _dataList;
    
    public TbSkill(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hok.SkillCfg>(n);
        _dataList = new System.Collections.Generic.List<hok.SkillCfg>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hok.SkillCfg _v;
            _v = global::GameConfig.hok.SkillCfg.DeserializeSkillCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, hok.SkillCfg> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<hok.SkillCfg> DataList => _dataList;

    public hok.SkillCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hok.SkillCfg Get(int key) => _dataMap[key];
    public hok.SkillCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

