
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// HOK目标规则配置(占位)
/// </summary>
public partial class TbTargetRule
{
    private readonly System.Collections.Generic.Dictionary<int, hok.TargetRule> _dataMap;
    private readonly System.Collections.Generic.List<hok.TargetRule> _dataList;
    
    public TbTargetRule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hok.TargetRule>(n);
        _dataList = new System.Collections.Generic.List<hok.TargetRule>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hok.TargetRule _v;
            _v = global::GameConfig.hok.TargetRule.DeserializeTargetRule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, hok.TargetRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<hok.TargetRule> DataList => _dataList;

    public hok.TargetRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hok.TargetRule Get(int key) => _dataMap[key];
    public hok.TargetRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

