
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
/// <summary>
/// HOK单位配置
/// </summary>
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, hok.Unit> _dataMap;
    private readonly System.Collections.Generic.List<hok.Unit> _dataList;
    
    public TbUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hok.Unit>(n);
        _dataList = new System.Collections.Generic.List<hok.Unit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hok.Unit _v;
            _v = global::GameConfig.hok.Unit.DeserializeUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, hok.Unit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<hok.Unit> DataList => _dataList;

    public hok.Unit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hok.Unit Get(int key) => _dataMap[key];
    public hok.Unit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

