
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.hok
{
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResName = _buf.ReadString();
        HitHeight = _buf.ReadFloat();
        Hp = _buf.ReadInt();
        Def = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        ColliderType = _buf.ReadInt();
        ColliderRadius = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); PassiveBuffs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PassiveBuffs.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Skills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Skills.Add(_e0);}}
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new hok.Unit(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string ResName;
    /// <summary>
    /// 受击高度
    /// </summary>
    public readonly float HitHeight;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Def;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 碰撞类型
    /// </summary>
    public readonly int ColliderType;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float ColliderRadius;
    /// <summary>
    /// 被动Buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> PassiveBuffs;
    /// <summary>
    /// 技能列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
   
    public const int __ID__ = -594215666;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resName:" + ResName + ","
        + "hitHeight:" + HitHeight + ","
        + "hp:" + Hp + ","
        + "def:" + Def + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "colliderType:" + ColliderType + ","
        + "colliderRadius:" + ColliderRadius + ","
        + "passiveBuffs:" + Luban.StringUtil.CollectionToString(PassiveBuffs) + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "}";
    }
}
}

